import { Inter } from "next/font/google";
import Header from "./component/header";
import "./globals.css";
import Footer from "./component/footer";
import { Mulish } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 
const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export default function RootLayout({ children }) {
  return (
  <ClerkProvider>
    <html lang="en" className={mulish.className}>
      
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
  );
}
